services:
  - type: web
    name: food-freshness-detector
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: HF_MODEL_REPO
        value: nathansekar/food-freshness-detector
